### ISSUE TITLE
目前windows存在framework/native中的cpp代码查找不到的情况

### ISSUE THREAD

**Issue by aqxuwenda** [journeyOS/as-aosp#2]
目前windows存在framework/native中的cpp代码查找不到的情况，尝试过修改cmakelists.txt，目前来看还没有解决这个问题

**Comment by i-rtfsc** [comment]
经沟通，在windows平台下如果Android工程根目录是 D:\code\aosp\
请不要写成 **D:\\code\\aosp\\**
正确的写法 **D:/code/aosp/**
