### ISSUE TITLE
源码阅读问题

### ISSUE THREAD

**Issue by HelloYmf** [journeyOS/as-aosp#7]
在local.properties中配置EXT_AOSP_ROOT后，并同步完成后，如何进行aosp源码的浏览，比如我想查看art/runtime模块下的代码？

**Comment by i-rtfsc** [comment]
win下判断IDE错误以及cmakelists解析path错误已经在提交中解决
https://github.com/i-rtfsc/as-aosp/commit/118d1567a85edfb95d303ce9491bbaa0a97f2167

更新代码即可。

**Comment by i-rtfsc** [comment]
暂无反馈问题，关闭。
